import { Potential } from "../Generic/enums";
import { ItemAddOption, ItemBaseOption, ItemEtcOption, ItemExceptionalOption, ItemStarForceOption, ItemTotalOption } from "./options";

export interface Equipment {
    item_equipment_part: string,
    item_equipment_slot: ItemEquipmentSlot,
    item_name: string,
    item_icon: string,
    item_description: string,
    item_shape_name: string,
    item_shape_icon: string,
    item_gender: string,
    item_total_option: ItemTotalOption,
    item_base_option: ItemBaseOption,
    potential_option_grade: Potential,
    additional_potential_option_grade: Potential,
    potential_option_flag: boolean,
    potential_option_1: string,
    potential_option_2: string,
    potential_option_3: string,
    additional_potential_option_flag: boolean,
    additional_potential_option_1: string,
    additional_potential_option_2: string,
    additional_potential_option_3: string,
    equipment_level_increase: number,
    item_exceptional_option: ItemExceptionalOption,
    item_add_option: ItemAddOption,
    growth_exp: number,
    growth_level: number,
    scroll_upgrade: number,
    cuttable_count: number,
    golden_hammer_flag: string,
    scroll_resilience_count: number,
    scroll_upgradeable_count: number,
    soul_name: string,
    soul_option: string,
    item_etc_option: ItemEtcOption,
    starforce: number,
    starforce_scroll_flag: string,
    item_starforce_option: ItemStarForceOption,
    special_ring_level: number,
    date_expire: string,
    maxStarforce: number
}

export enum ItemEquipmentSlot {
    Ring1 = "Ring1",
    Ring2 = "Ring2",
    Ring3 = "Ring3",
    Ring4 = "Ring4",
    Pendant = "Pendant",
    Pendant2 = "Pendant2",
    Weapon = "Weapon",
    Belt = "Belt",
    Hat = "Hat",
    FaceAccessory = "FaceAccessory",
    EyeAccessory = "EyeAccessory",
    Top = "Top",
    Bottom = "Bottom",
    Shoes = "Shoes",
    Earring = "Earring",
    ShoulderDecoration = "ShoulderDecoration",
    Glove = "Glove",
    Emblem = "Emblem",
    Badge = "Badge",
    Medal = "Medal",
    SecondaryWeapons = "SecondaryWeapons",
    Cape = "Cape",
    MechanicalHeart = "MechanicalHeart",
}