import { CharacterClass, Potential, ItemEquipmentSlot } from "@ruvice/my-maple-models"

export const ItemEquipmentSlotMapping: Record<string, ItemEquipmentSlot> = {
    "ring1" : ItemEquipmentSlot.Ring1,
    "ring2" : ItemEquipmentSlot.Ring2,
    "ring3" : ItemEquipmentSlot.Ring3,
    "ring4" : ItemEquipmentSlot.Ring4,
    "pendant" : ItemEquipmentSlot.Pendant,
    "pendant2" : ItemEquipmentSlot.Pendant2,
    "weapon" : ItemEquipmentSlot.Weapon,
    "belt" : ItemEquipmentSlot.Belt,
    "hat" : ItemEquipmentSlot.Hat,
    "faceaccessory" : ItemEquipmentSlot.FaceAccessory,
    "eyeaccessory" : ItemEquipmentSlot.EyeAccessory,
    "top" : ItemEquipmentSlot.Top,
    "bottom" : ItemEquipmentSlot.Bottom,
    "shoes" : ItemEquipmentSlot.Shoes,
    "earring" : ItemEquipmentSlot.Earring,
    "shoulderdecoration": ItemEquipmentSlot.ShoulderDecoration,
    "glove" : ItemEquipmentSlot.Glove,
    "emblem" : ItemEquipmentSlot.Emblem,
    "badge" : ItemEquipmentSlot.Badge,
    "medal" : ItemEquipmentSlot.Medal,
    "secondaryweapons" : ItemEquipmentSlot.SecondaryWeapons,
    "cape" : ItemEquipmentSlot.Cape,
    "mechanicalheart": ItemEquipmentSlot.MechanicalHeart
}

export const PotentialMapping: Record<string, Potential> = {
    "Rare": Potential.Rare,
    "Epic": Potential.Epic,
    "Unique": Potential.Unique,
    "Legendary": Potential.Legendary
}

export const CharacterClassMapping: Record<string, CharacterClass> = {
  "Hero": CharacterClass.Hero,
  "Paladin": CharacterClass.Paladin,
  "Dark Knight": CharacterClass.DarkKnight,
  "Soul Master": CharacterClass.SoulMaster,
  "Mihile": CharacterClass.Mihile,
  "Blaster": CharacterClass.Blaster,
  "Demon Slayer": CharacterClass.DemonSlayer,
  "Demon Avenger": CharacterClass.DemonAvenger,
  "Aran": CharacterClass.Aran,
  "Kaiser": CharacterClass.Kaiser,
  "Adele": CharacterClass.Adele,
  "Zero": CharacterClass.Zero,
  "ArchMage F/P": CharacterClass.ArchMageFP,
  "ArchMage I/L": CharacterClass.ArchMageIL,
  "Bishop": CharacterClass.Bishop,
  "Flame Wizard": CharacterClass.FlameWizard,
  "Battle Mage": CharacterClass.BattleMage,
  "Evan": CharacterClass.Evan,
  "Luminous": CharacterClass.Luminous,
  "Illium": CharacterClass.Illium,
  "Lara": CharacterClass.Lara,
  "Kinesis": CharacterClass.Kinesis,
  "Bowmaster": CharacterClass.Bowmaster,
  "Crossbow Master": CharacterClass.CrossbowMaster,
  "Pathfinder": CharacterClass.Pathfinder,
  "Wind Breaker": CharacterClass.WindBreaker,
  "Wild Hunter": CharacterClass.WildHunter,
  "Mercedes": CharacterClass.Mercedes,
  "Kaine": CharacterClass.Kaine,
  "Night Lord": CharacterClass.NightLord,
  "Shadower": CharacterClass.Shadower,
  "Blade Master": CharacterClass.BladeMaster,
  "Night Walker": CharacterClass.NightWalker,
  "Xenon": CharacterClass.Xenon,
  "Phantom": CharacterClass.Phantom,
  "Cadena": CharacterClass.Cadena,
  "Khali": CharacterClass.Khali,
  "HoYoung": CharacterClass.HoYoung,
  "Viper": CharacterClass.Viper,
  "Captain": CharacterClass.Captain,
  "Cannon Master": CharacterClass.CannonMaster,
  "Striker": CharacterClass.Striker,
  "Mechanic": CharacterClass.Mechanic,
  "Eunwol": CharacterClass.Eunwol,
  "Angelic Buster": CharacterClass.AngelicBuster,
  "Ark": CharacterClass.Ark,
  "Hayato": CharacterClass.Hayato,
  "Kanna": CharacterClass.Kanna,
};
